### ISSUE TITLE
[ About ] 애니메이션 올라오는 시간 수정 

### ISSUE THREAD

**Issue by seochan99** [LikeLion-at-DGU/moin_frontend#99]
### 📝 check-lists
<img width="1459" alt="Screenshot 2023-08-16 at 4 54 33 AM" src="https://github.com/LikeLion-at-DGU/moin_frontend/assets/78739194/106d92e4-cf04-4d6c-85f1-dcfd221db9d9">

<img width="1506" alt="Screenshot 2023-08-16 at 4 54 41 AM" src="https://github.com/LikeLion-at-DGU/moin_frontend/assets/78739194/f3a382c8-d8c5-4da5-84f9-eab3c345a362">

좀더더 빨리
- [ ]

**Comment by shimseohyun** [comment]
완료
